# Generated by Django 5.0.7 on 2024-07-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('py', 'Python'), ('js', 'Javascript'), ('cpp', 'C++'), ('html', 'HTML')], max_length=30),
        ),
    ]
